stages:
  download_data:
    cmd: kaggle competitions download -c petfinder-pawpularity-score -p data/
    outs:
    - data/petfinder-pawpularity-score.zip
  unzip_data:
    cmd: unzip data/petfinder-pawpularity-score.zip -d data/
    deps:
    - data/petfinder-pawpularity-score.zip
    outs:
    - data/sample_submission.csv
    - data/test
    - data/test.csv
    - data/train
    - data/train.csv
  create_folds:
    cmd: python pipe/create_folds.py
    params:
    - create_folds
    deps:
    - data/train.csv
    - pipe/create_folds.py
    outs:
    - data/train_folds.csv
  train_one:
    cmd: python pipe/train.py
    params:
    - train_one
    deps:
    - data/train
    - pipe/train.py
    - data/train_folds.csv
    outs:
    - ckpts/model_one_fold0.ckpt
    - ckpts/model_one_fold1.ckpt
    - ckpts/model_one_fold2.ckpt
    - ckpts/model_one_fold3.ckpt
    - ckpts/model_one_fold4.ckpt
    - preds/model_one_fold0.npy
    - preds/model_one_fold1.npy
    - preds/model_one_fold2.npy
    - preds/model_one_fold3.npy
    - preds/model_one_fold4.npy
    metrics:
    - metrics/model_one.json:
        cache: False

