stages:
  download_data:
    cmd: kaggle competitions download -c petfinder-pawpularity-score -p data/
    outs:
    - data/petfinder-pawpularity-score.zip
  unzip_data:
    cmd: unzip data/petfinder-pawpularity-score.zip -d data/
    deps:
    - data/petfinder-pawpularity-score.zip
    outs:
    - data/sample_submission.csv
    - data/test
    - data/test.csv
    - data/train
    - data/train.csv
  create_folds:
    cmd: python pipe/create_folds.py
    deps:
    - data/train.csv
    - pipe/create_folds.py
    outs:
    - data/train_folds.csv
  train_one:
    cmd: python pipe/train.py
    deps:
    - data/train
    - pipe/train.py
    - data/train_folds.csv
    outs:
    - ckpts/arch=resnet18_sz=224_fold=0.ckpt
    - ckpts/arch=resnet18_sz=224_fold=1.ckpt
    - ckpts/arch=resnet18_sz=224_fold=2.ckpt
    - ckpts/arch=resnet18_sz=224_fold=3.ckpt
    - ckpts/arch=resnet18_sz=224_fold=4.ckpt
