stages:
  download_data:
    cmd: kaggle competitions download -c petfinder-pawpularity-score -p data/
    outs:
    - data/petfinder-pawpularity-score.zip
  unzip_data:
    cmd: unzip data/petfinder-pawpularity-score.zip -d data/
    deps:
    - data/petfinder-pawpularity-score.zip
    outs:
    - data/sample_submission.csv
    - data/test
    - data/test.csv
    - data/train
    - data/train.csv
  remove_duplicates:
    cmd: python pipe/remove_duplicate_images.py
    deps:
    - data/train
    - pipe/remove_duplicate_images.py
    outs:
    - data/train_deduped.csv
  create_folds:
    cmd: python pipe/create_folds.py
    params:
    - create_folds
    deps:
    - data/train_deduped.csv
    - pipe/create_folds.py
    outs:
    - data/train_folds.csv
  resize_images:
    cmd: python pipe/resize_images.py
    deps:
    - data/test
    - data/train
    - pipe/resize_images.py
    params:
    - resize
    outs:
    - data/test_224/
    - data/train_224/
    - data/test_384/
    - data/train_384/
  train_one:
    cmd: python pipe/train_one.py
    params:
    - train_one
    deps:
    - pipe/train_one.py
    - data/train_384
    - data/train_folds.csv
    outs:
    - ckpts/model_one_fold0.ckpt
    - ckpts/model_one_fold1.ckpt
    - ckpts/model_one_fold2.ckpt
    - ckpts/model_one_fold3.ckpt
    - ckpts/model_one_fold4.ckpt
    - preds/model_one_fold0.npy
    - preds/model_one_fold1.npy
    - preds/model_one_fold2.npy
    - preds/model_one_fold3.npy
    - preds/model_one_fold4.npy
    metrics:
    - metrics/model_one.json:
        cache: false
  train_two:
    cmd: python pipe/train_two.py
    params:
    - train_two
    deps:
    - pipe/train_two.py
    - data/train_224
    - data/train_folds.csv
    outs:
    - ckpts/model_two_fold0.ckpt
    - ckpts/model_two_fold1.ckpt
    - ckpts/model_two_fold2.ckpt
    - ckpts/model_two_fold3.ckpt
    - ckpts/model_two_fold4.ckpt
    - preds/model_two_fold0.npy
    - preds/model_two_fold1.npy
    - preds/model_two_fold2.npy
    - preds/model_two_fold3.npy
    - preds/model_two_fold4.npy
    metrics:
    - metrics/model_two.json:
        cache: false
