stages:
  download_data:
    cmd: kaggle competitions download -c petfinder-pawpularity-score -p data/
    outs:
    - data/petfinder-pawpularity-score.zip
  unzip_data:
    cmd: unzip data/petfinder-pawpularity-score.zip -d data/
    deps:
    - data/petfinder-pawpularity-score.zip
    outs:
    - data/sample_submission.csv
    - data/test
    - data/test.csv
    - data/train
    - data/train.csv
  remove_duplicates:
    cmd: python pipe/remove_duplicate_images.py
    deps:
    - data/train
    - pipe/remove_duplicate_images.py
    outs:
    - data/train_deduped.csv
  create_folds:
    cmd: python pipe/create_folds.py
    params:
    - create_folds
    deps:
    - data/train_deduped.csv
    - pipe/create_folds.py
    outs:
    - data/train_folds_all.csv
  train_zero:
    cmd: python pipe/train_zero.py
    params:
    - train_zero
    deps:
    - pipe/train_zero.py
    - data/train
    - data/train_folds_all.csv
    outs:
    - ckpts/model_zero_fold0.ckpt
    - ckpts/model_zero_fold1.ckpt
    - ckpts/model_zero_fold2.ckpt
    - ckpts/model_zero_fold3.ckpt
    - ckpts/model_zero_fold4.ckpt
    - preds/model_zero_oof.npy
    metrics:
    - metrics/model_zero.json:
        cache: false
  remove_hardest_samples:
    cmd: python pipe/remove_hardest_samples.py
    params:
    - remove_hardest_samples
    deps:
    - data/train_folds_all.csv
    - pipe/remove_hardest_samples.py
    - ckpts/model_zero_fold0.ckpt
    - ckpts/model_zero_fold1.ckpt
    - ckpts/model_zero_fold2.ckpt
    - ckpts/model_zero_fold3.ckpt
    - ckpts/model_zero_fold4.ckpt
    outs:
    - data/train_folds.csv
  train_one:
    cmd: python pipe/train_one.py
    params:
    - train_one
    deps:
    - pipe/train_one.py
    - data/train
    - data/train_folds.csv
    outs:
    - ckpts/model_one_fold0.ckpt
    - ckpts/model_one_fold1.ckpt
    - ckpts/model_one_fold2.ckpt
    - ckpts/model_one_fold3.ckpt
    - ckpts/model_one_fold4.ckpt
    - preds/model_one_oof.npy
    metrics:
    - metrics/model_one.json:
        cache: false
  train_two:
    cmd: python pipe/train_two.py
    params:
    - train_two
    deps:
    - pipe/train_two.py
    - data/train
    - data/train_folds.csv
    outs:
    - ckpts/model_two_fold0.ckpt
    - ckpts/model_two_fold1.ckpt
    - ckpts/model_two_fold2.ckpt
    - ckpts/model_two_fold3.ckpt
    - ckpts/model_two_fold4.ckpt
    - preds/model_two_oof.npy
    metrics:
    - metrics/model_two.json:
        cache: false
  train_three:
    cmd: python pipe/train_three.py
    params:
    - train_three
    deps:
    - pipe/train_three.py
    - data/train
    - data/train_folds.csv
    outs:
    - ckpts/model_three_fold0.ckpt
    - ckpts/model_three_fold1.ckpt
    - ckpts/model_three_fold2.ckpt
    - ckpts/model_three_fold3.ckpt
    - ckpts/model_three_fold4.ckpt
    - preds/model_three_oof.npy
    metrics:
    - metrics/model_three.json:
        cache: false
  train_four:
    cmd: python pipe/train_four.py
    params:
    - train_four
    deps:
    - pipe/train_four.py
    - data/train
    - data/train_folds.csv
    outs:
    - ckpts/model_four_fold0.ckpt
    - ckpts/model_four_fold1.ckpt
    - ckpts/model_four_fold2.ckpt
    - ckpts/model_four_fold3.ckpt
    - ckpts/model_four_fold4.ckpt
    - preds/model_four_oof.npy
    metrics:
    - metrics/model_four.json:
        cache: false
  ensemble:
    cmd: python pipe/ensemble.py
    params:
    - ensemble
    deps:
    - data/train_folds.csv
    - pipe/ensemble.py
    - preds/model_one_oof.npy
    - preds/model_two_oof.npy
    - preds/model_three_oof.npy
    - preds/model_four_oof.npy
    outs:
    - ckpts/model_ensemble.joblib
    metrics:
    - metrics/model_ensemble.json:
        cache: false
  download_extra_data:
    cmd: kaggle competitions download -c petfinder-adoption-prediction -p data/petfinder-adoption-prediction
    outs:
    - data/petfinder-adoption-prediction/petfinder-adoption-prediction.zip
  unzip_extra_data:
    cmd: unzip data/petfinder-adoption-prediction/petfinder-adoption-prediction.zip
      -d data/petfinder-adoption-prediction/
    deps:
    - data/petfinder-adoption-prediction/petfinder-adoption-prediction.zip
    outs:
    - data/petfinder-adoption-prediction/BreedLabels.csv
    - data/petfinder-adoption-prediction/ColorLabels.csv
    - data/petfinder-adoption-prediction/PetFinder-BreedLabels.csv
    - data/petfinder-adoption-prediction/PetFinder-ColorLabels.csv
    - data/petfinder-adoption-prediction/PetFinder-StateLabels.csv
    - data/petfinder-adoption-prediction/StateLabels.csv
    - data/petfinder-adoption-prediction/breed_labels.csv
    - data/petfinder-adoption-prediction/color_labels.csv
    - data/petfinder-adoption-prediction/state_labels.csv
    - data/petfinder-adoption-prediction/test/
    - data/petfinder-adoption-prediction/test_images
    - data/petfinder-adoption-prediction/test_metadata
    - data/petfinder-adoption-prediction/test_sentiment
    - data/petfinder-adoption-prediction/train/
    - data/petfinder-adoption-prediction/train_images/
    - data/petfinder-adoption-prediction/train_metadata
    - data/petfinder-adoption-prediction/train_sentiment
  organize_extra_images:
    cmd: mkdir data/extra && find data/petfinder-adoption-prediction/ -name '*.jpg'
      -exec cp {} data/extra/ \;
    deps:
    - data/petfinder-adoption-prediction/test_images/
    - data/petfinder-adoption-prediction/train_images/
    outs:
    - data/extra
  download_extra_data2:
    cmd: kaggle competitions download -c dogs-vs-cats -p data/dogs-vs-cats
    outs:
    - data/dogs-vs-cats/dogs-vs-cats.zip
  unzip_extra_data2:
    cmd: unzip data/dogs-vs-cats/dogs-vs-cats.zip
      -d data/dogs-vs-cats/ && unzip data/dogs-vs-cats/train.zip -d data/dogs-vs-cats/images/ && unzip data/dogs-vs-cats/test1.zip -d data/dogs-vs-cats/images/
    deps:
    - data/dogs-vs-cats/dogs-vs-cats.zip
    outs:
    - data/dogs-vs-cats/train.zip
    - data/dogs-vs-cats/test1.zip
    - data/dogs-vs-cats/sampleSubmission.csv
    - data/dogs-vs-cats/images/
  organize_extra_images2:
    cmd: mkdir data/extra2 && find data/dogs-vs-cats/ -name '*.jpg'
      -exec cp {} data/extra2/ \;
    deps:
    - data/dogs-vs-cats/images/
    outs:
    - data/extra2
  pseudo_labeling_extra2:
    cmd: python pipe/pseudo_label_extra2.py
    params:
    - pseudo_labeling
    deps:
    - data/train_folds.csv
    - data/extra2/
    - pipe/pseudo_label_extra2.py
    - ckpts/model_one_fold0.ckpt
    - ckpts/model_one_fold1.ckpt
    - ckpts/model_one_fold2.ckpt
    - ckpts/model_one_fold3.ckpt
    - ckpts/model_one_fold4.ckpt
    - ckpts/model_two_fold0.ckpt
    - ckpts/model_two_fold1.ckpt
    - ckpts/model_two_fold2.ckpt
    - ckpts/model_two_fold3.ckpt
    - ckpts/model_two_fold4.ckpt
    - ckpts/model_three_fold0.ckpt
    - ckpts/model_three_fold1.ckpt
    - ckpts/model_three_fold2.ckpt
    - ckpts/model_three_fold3.ckpt
    - ckpts/model_three_fold4.ckpt
    - ckpts/model_four_fold0.ckpt
    - ckpts/model_four_fold1.ckpt
    - ckpts/model_four_fold2.ckpt
    - ckpts/model_four_fold3.ckpt
    - ckpts/model_four_fold4.ckpt
    outs:
    - data/extra2.csv
  train_one_extra2:
    cmd: python pipe/train_one_extra2.py
    params:
    - train_one_extra2
    deps:
    - pipe/train_one_extra2.py
    - data/train
    - data/extra2
    - data/train_folds.csv
    - data/extra2.csv
    outs:
    - ckpts/model_one_extra2_fold0.ckpt
    - ckpts/model_one_extra2_fold1.ckpt
    - ckpts/model_one_extra2_fold2.ckpt
    - ckpts/model_one_extra2_fold3.ckpt
    - ckpts/model_one_extra2_fold4.ckpt
    - preds/model_one_extra2_oof.npy
    metrics:
    - metrics/model_one_extra2.json:
        cache: false
  train_two_extra2:
    cmd: python pipe/train_two_extra2.py
    params:
    - train_two_extra2
    deps:
    - pipe/train_two_extra2.py
    - data/train
    - data/extra2
    - data/train_folds.csv
    - data/extra2.csv
    outs:
    - ckpts/model_two_extra2_fold0.ckpt
    - ckpts/model_two_extra2_fold1.ckpt
    - ckpts/model_two_extra2_fold2.ckpt
    - ckpts/model_two_extra2_fold3.ckpt
    - ckpts/model_two_extra2_fold4.ckpt
    - preds/model_two_extra2_oof.npy
    metrics:
    - metrics/model_two_extra2.json:
        cache: false
  train_three_extra2:
    cmd: python pipe/train_three_extra2.py
    params:
    - train_three_extra2
    deps:
    - pipe/train_three_extra2.py
    - data/train
    - data/extra2
    - data/train_folds.csv
    - data/extra2.csv
    outs:
    - ckpts/model_three_extra2_fold0.ckpt
    - ckpts/model_three_extra2_fold1.ckpt
    - ckpts/model_three_extra2_fold2.ckpt
    - ckpts/model_three_extra2_fold3.ckpt
    - ckpts/model_three_extra2_fold4.ckpt
    - preds/model_three_extra2_oof.npy
    metrics:
    - metrics/model_three_extra2.json:
        cache: false
  train_four_extra2:
    cmd: python pipe/train_four_extra2.py
    params:
    - train_four_extra2
    deps:
    - pipe/train_four_extra2.py
    - data/train
    - data/extra2
    - data/train_folds.csv
    - data/extra2.csv
    outs:
    - ckpts/model_four_extra2_fold0.ckpt
    - ckpts/model_four_extra2_fold1.ckpt
    - ckpts/model_four_extra2_fold2.ckpt
    - ckpts/model_four_extra2_fold3.ckpt
    - ckpts/model_four_extra2_fold4.ckpt
    - preds/model_four_extra2_oof.npy
    metrics:
    - metrics/model_four_extra2.json:
        cache: false
  train_five:
    cmd: python pipe/train_five.py
    params:
    - train_one_extra2
    deps:
    - pipe/train_five.py
    - data/train
    - ckpts/model_one_extra2_fold0.ckpt
    - ckpts/model_one_extra2_fold1.ckpt
    - ckpts/model_one_extra2_fold2.ckpt
    - ckpts/model_one_extra2_fold3.ckpt
    - ckpts/model_one_extra2_fold4.ckpt
    - data/train_folds.csv
    outs:
    - ckpts/model_five_fold0.ckpt
    - ckpts/model_five_fold1.ckpt
    - ckpts/model_five_fold2.ckpt
    - ckpts/model_five_fold3.ckpt
    - ckpts/model_five_fold4.ckpt
    - preds/model_five_oof.npy
    metrics:
    - metrics/model_five.json:
        cache: false
  ensemble_final:
    cmd: python pipe/ensemble_final.py
    params:
    - ensemble_final
    deps:
    - data/train_folds.csv
    - pipe/ensemble_final.py
    - preds/model_one_extra2_oof.npy
    - preds/model_two_extra2_oof.npy
    - preds/model_three_extra2_oof.npy
    - preds/model_four_extra2_oof.npy
    - preds/model_five_oof.npy
    outs:
    - ckpts/model_ensemble_final.joblib
    metrics:
    - metrics/model_ensemble_final.json:
        cache: false