create_folds:
  seed: 6822
  k: 5

train_one:
  seed: 46
  fold: -1
  # problem
  metric: "rmse"
  metric_mode: "min"
  # imput images
  train_data: "data/train"
  sz: 224
  # model
  arch: "resnet50d"
  epochs: 5
  bs: 128
  auto_batch_size: False
  accumulate_grad_batches: 1
  precision: 32
  # augmentations
  n_tfms: 0
  magn: 0
  aug: "none"
  # regularization
  dropout: 0.0
  wd: 0.0
  label_smoothing: 0.0
  # optimizer
  loss: "bce_with_logits"
  opt: "adam"
  sched: "onecycle"
  lr: 0.01
  auto_lr: False
  mom: 0.9
