create_folds:
  seed: 6822
  k: 5

resize:
  sz: [224, 384]

train_one:
  seed: 46
  fold: -1
  # problem
  metric: rmse
  metric_mode: min
  # input images
  train_data: data/train_384
  # model
  arch: swin_large_patch4_window12_384
  pretrained: true
  epochs: 10
  bs: 8
  auto_batch_size: false
  accumulate_grad_batches: 1
  precision: 32
  # augmentations
  n_tfms: 2
  magn: 3
  sz: 384
  # regularization
  dropout: 0.0
  wd: 0.0
  label_smoothing: 0.0
  # optimizer
  loss: bce_with_logits
  opt: adam
  sched: onecycle
  lr: 0.000025
  auto_lr: false
  mom: 0.9

train_two:
  seed: 46
  fold: -1
  # problem
  metric: rmse
  metric_mode: min
  # input images
  train_data: data/train_224
  # model
  arch: swin_large_patch4_window7_224
  pretrained: true
  epochs: 6
  bs: 40
  auto_batch_size: false
  accumulate_grad_batches: 1
  precision: 32
  # augmentations
  n_tfms: 2
  magn: 3
  sz: 224
  # regularization
  dropout: 0.0
  wd: 0.0
  label_smoothing: 0.0
  # optimizer
  loss: bce_with_logits
  opt: adam
  sched: onecycle
  lr: 0.000125
  auto_lr: false
  mom: 0.9