create_folds:
  seed: 42
  k: [5, 10]

resize:
  sz: [224, 384]

train_one:
  name: one
  seed: 5899
  n_folds: 5
  fold: -1
  # problem
  metric: rmse
  metric_mode: min
  # input images
  train_data: data/train_384
  # model
  arch: swin_large_patch4_window12_384
  pretrained: true
  epochs: 10
  bs: 8
  auto_batch_size: false
  accumulate_grad_batches: 1
  precision: 16
  # augmentations
  use_normalize: true
  n_tfms: 2
  magn: 3
  sz: 384
  use_mix: 0
  mix_p: 0.0
  resize: -1
  # regularization
  dropout: 0.0
  wd: 0.0
  label_smoothing: 0.1
  # optimizer
  loss: bce_with_logits
  opt: adamw
  sched: cosine
  lr: 0.000003
  warmup: 0.1
  auto_lr: false
  mom: 0.9

train_two:
  name: two
  seed: 7591
  n_folds: 5
  fold: -1
  # problem
  metric: rmse
  metric_mode: min
  # input images
  train_data: data/train_224
  # model
  arch: swin_large_patch4_window7_224
  pretrained: true
  epochs: 6
  bs: 40
  auto_batch_size: false
  accumulate_grad_batches: 1
  precision: bf16
  # augmentations
  use_normalize: true
  n_tfms: 2
  magn: 3
  sz: 224
  use_mix: 0
  mix_p: 0.0
  resize: -1
  # regularization
  dropout: 0.0
  wd: 0.0
  label_smoothing: 0.1
  # optimizer
  loss: bce_with_logits
  opt: adamw
  sched: cosine
  warmup_epochs: 1
  lr: 0.000015
  auto_lr: false
  mom: 0.9
